"""Faz 8: order odeme alanlari

Revision ID: 94e5ed192b5d
Revises: 78143dfaac02
Create Date: 2026-06-07 11:40:13.180090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94e5ed192b5d'
down_revision: Union[str, Sequence[str], None] = '78143dfaac02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        batch_op.add_column(sa.Column('provider_payment_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_payment_token'), ['payment_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_payment_token'))
        batch_op.drop_column('provider_payment_id')
        batch_op.drop_column('payment_token')

    # ### end Alembic commands ###
